# -*- coding: utf-8 -*-
"""uady_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGTh32m0u1QJllNcKxVSRBKK0Xe9dWdk

##Instalando las librerías necesarias
"""

!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local

import sys
sys.path.append('/usr/local/lib/python3.10/site-packages/')

!python -m ipykernel install --user --name=py310 --display-name="Python 3.10"

!python --version

!pip install pycaret[full]

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!pip install fastapi
!pip install uvicorn

from sklearn.preprocessing import LabelEncoder

from pycaret.utils import version
version()

!python --version

"""## LLamando al modelo en PYCARET"""

from pycaret.regression import *

datos= "https://github.com/gchavez83/Analitica/raw/main/Salida_UADY_ML_26.xlsx" ##Bd llamadas desde github

df = pd.read_excel(datos)
#df.drop(columns="Unnamed: 0", inplace=True)
df

df.info()

df.isnull().sum().sort_values(ascending=False)

print(pd.value_counts(df['ESTATUS'], sort = True))

count_classes = pd.value_counts(df['ESTATUS'], sort = True)
count_classes.plot(kind = 'bar', rot=0)
plt.xticks(range(2))
plt.title("Frequency by observation number")
plt.xlabel("Estatus")
plt.ylabel("Number of Observations")

df.describe()

df.head(100)

columnas_numericas = ['Avg__indice_Ceneval', 'Avg__indice_Pensamiento_Matemático', 'POSICIÓN']

sub_df = df[columnas_numericas]

matriz_correlacion = sub_df.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(matriz_correlacion, annot=True, cmap='coolwarm', center=0)
plt.title('Matriz de Correlación')
plt.show()

"""##División del Conjunto de Datos"""

datos = df.sample(frac=0.75, random_state=0)
datos_no_vistos = df.drop(datos.index)

datos.reset_index(inplace=True, drop=True)
datos_no_vistos.reset_index(inplace=True, drop=True)

print("Datos para Modelar: " + str(datos.shape))
print("Datos no vistos para Predicciones: " + str(datos_no_vistos.shape))

regresion = setup(data = datos, target = "POSICIÓN", session_id=123, ignore_features= ['FOLIO CENEVAL', 'ESTATUS', 'Ciclo'], categorical_features = ['Abv.1'], max_encoding_ohe = 49)

get_config('X_train')

help(deploy_model)

"""##Comparando algoritmos de Regresión"""

mejor_modelo = compare_models()

mejor_modelo

type(mejor_modelo)

"""##Creación del MODELO"""

modelo = create_model("lightgbm")
print(modelo)

modelo_catboost = create_model("catboost")
print(modelo_catboost)

modelo_xgboost = create_model("xgboost")
print(modelo_xgboost)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
eda(display_format= 'svg')

type(modelo)

#create_api(modelo, 'modelo_api')
#!python modelo_api.py

create_app(modelo)

create_app(modelo_catboost)

create_app(modelo_xgboost)

print(convert_model(modelo, language= 'php'))

print(convert_model(modelo, language= 'r'))

print(convert_model(modelo_xgboost, language= 'php'))

optimizar_modelo = tune_model(modelo)
print(optimizar_modelo)

print(convert_model(optimizar_modelo, language= 'php'))

"""##Visualización del MODELO"""

evaluate_model(modelo)

predict_model(modelo)

final_modelo = finalize_model(modelo)
print(final_modelo)

predict_model(final_modelo)

"""##Predecir sobre datos no vistos"""

datos_no_vistos_prediccion = predict_model(final_modelo, data=datos_no_vistos)
datos_no_vistos_prediccion.head(20)

save_model(final_modelo,"/content/modelo_regresion_lightgbm_Uady_25")