# -*- coding: utf-8 -*-
"""uady_clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCf4efCVZVOFs1cu5D-m2P9wJPC4Grg6

#Instalando las librerías necesarias
"""

!pip install pycaret[full]

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!pip install fastapi

!pip install uvicorn

from sklearn.preprocessing import LabelEncoder

from pycaret.utils import version
version()

from pycaret.classification import *

datos= "https://github.com/gchavez83/Analitica/raw/main/Salida_UADY_ML_25.xlsx" ##Bd llamadas desde github

df = pd.read_excel(datos)
#df.drop(columns="Unnamed: 0", inplace=True)
df

df.info()

df.describe()

#df['ESTATUS'] = df['ESTATUS'].replace({"Admitido":1, "No admitido":0 })

df.head(10)

"""##División del Conjunto de Datos"""

datos = df.sample(frac=0.75, random_state=0)
datos_no_vistos = df.drop(datos.index)

datos.reset_index(inplace=True, drop=True)
datos_no_vistos.reset_index(inplace=True, drop=True)

print("Datos para Modelar: " + str(datos.shape))
print("Datos no vistos para Predicciones: " + str(datos_no_vistos.shape))

clasificacion = setup(data = datos, target = "ESTATUS", session_id=123, ignore_features= ['Ciclo', 'FOLIO CENEVAL', 'POSICIÓN'], fix_imbalance= True, categorical_features = ['Abv.1'], max_encoding_ohe = 49)

get_config('X_train')

help(deploy_model)

"""##Comparando algoritmos de Clasificación"""

mejor_modelo = compare_models(sort = "Recall")

mejor_modelo

type(mejor_modelo)

"""##Creación del MODELO"""

modelo = create_model("lightgbm")
print(modelo)

modelo_catboost = create_model("catboost")
print(modelo_catboost)

eda(display_format= 'svg')

config = clasificacion.get_config()
print (config)

type(modelo)

#create_api(modelo, 'modelo_api')

#!python modelo_api.py

#!pip install pyngrok

#from pyngrok import ngrok

# Inicia el servidor
!python modelo_api.py &

# Obtén la URL pública del túnel
public_url = ngrok.connect(8000).public_url

print(f"¡El servidor está disponible en {public_url}!")

create_app(modelo)

print(convert_model(modelo, language= 'php'))

optimizar_modelo = tune_model(modelo)
print(optimizar_modelo)

print(convert_model(optimizar_modelo, language= 'php'))

#optimizar_modelo_2 = tune_model(modelo_2)
#print(optimizar_modelo)

"""##Visualización del MODELO"""

plot_model(modelo, plot = 'auc')

plot_model(modelo, plot = 'confusion_matrix')

evaluate_model(modelo)

predict_model(modelo)

final_modelo = finalize_model(modelo)
print(final_modelo)

predict_model(final_modelo)

"""##Predecir sobre datos no vistos"""

datos_no_vistos_prediccion = predict_model(final_modelo, data=datos_no_vistos)
datos_no_vistos_prediccion.head()

save_model(final_modelo,"/content/modelo_lightgbm_Uady_25")